### ISSUE TITLE
Code cleanup

### ISSUE THREAD

**Issue by mikenikles** [WebstoneHQ/platform#108]
A couple of things to address:
- [x] Centralize how we determine which stack is full-stack vs frontend & backend (#110)
- [x] Centralize how we parse a stack and determine what the frontend stack & what the backend stack is (#110)
- [x] Use SvelteKit's built-in form actions / enhance (#111)
